/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SuperRouteImport } from './routes/super'
import { Route as SuperAgenciesRouteImport } from './routes/super.agencies'
import { Route as SuperDatabaseRouteImport } from './routes/super.database'
import { Route as SuperUsersRouteImport } from './routes/super.users'
import { Route as UsersInvitesRouteImport } from './routes/users.invites'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAgenciesRoute = SuperAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => SuperRoute,
} as any)
const SuperDatabaseRoute = SuperDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => SuperRoute,
} as any)
const SuperUsersRoute = SuperUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperRoute,
} as any)
const UsersInvitesRoute = UsersInvitesRouteImport.update({
  id: '/users/invites',
  path: '/users/invites',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/super': typeof SuperRouteWithChildren
  '/super/agencies': typeof SuperAgenciesRoute
  '/super/database': typeof SuperDatabaseRoute
  '/super/users': typeof SuperUsersRoute
  '/users/invites': typeof UsersInvitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/super': typeof SuperRouteWithChildren
  '/super/agencies': typeof SuperAgenciesRoute
  '/super/database': typeof SuperDatabaseRoute
  '/super/users': typeof SuperUsersRoute
  '/users/invites': typeof UsersInvitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/super': typeof SuperRouteWithChildren
  '/super/agencies': typeof SuperAgenciesRoute
  '/super/database': typeof SuperDatabaseRoute
  '/super/users': typeof SuperUsersRoute
  '/users/invites': typeof UsersInvitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sign-up'
    | '/super'
    | '/super/agencies'
    | '/super/database'
    | '/super/users'
    | '/users/invites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/super'
    | '/super/agencies'
    | '/super/database'
    | '/super/users'
    | '/users/invites'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/sign-up'
    | '/super'
    | '/super/agencies'
    | '/super/database'
    | '/super/users'
    | '/users/invites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
  SuperRoute: typeof SuperRouteWithChildren
  UsersInvitesRoute: typeof UsersInvitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/agencies': {
      id: '/super/agencies'
      path: '/agencies'
      fullPath: '/super/agencies'
      preLoaderRoute: typeof SuperAgenciesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/database': {
      id: '/super/database'
      path: '/database'
      fullPath: '/super/database'
      preLoaderRoute: typeof SuperDatabaseRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/users': {
      id: '/super/users'
      path: '/users'
      fullPath: '/super/users'
      preLoaderRoute: typeof SuperUsersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/users/invites': {
      id: '/users/invites'
      path: '/users/invites'
      fullPath: '/users/invites'
      preLoaderRoute: typeof UsersInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SuperRouteChildren {
  SuperAgenciesRoute: typeof SuperAgenciesRoute
  SuperDatabaseRoute: typeof SuperDatabaseRoute
  SuperUsersRoute: typeof SuperUsersRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperAgenciesRoute: SuperAgenciesRoute,
  SuperDatabaseRoute: SuperDatabaseRoute,
  SuperUsersRoute: SuperUsersRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
  SuperRoute: SuperRouteWithChildren,
  UsersInvitesRoute: UsersInvitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
